### PR TITLE
fix(android): Delete stale refs

### LINKED ISSUE #129: [Android] Calling Bugsnag.Notify multiple times per frame will crash the app
### Description
Call Bugsnag.Notify multiple times per frame will crash the app

### Issue
   JNI ERROR (app bug): local reference table overflow (max=512)
   at BugsnagUnity.NativeInterface.DictionaryFromJavaMap (intptr)

It looks like this `DictionaryFromJavaMap()` method in `NativeInterface.cs` isn't deleting all the local references it is creating. So if you run it enough in the same frame, it will crash due to this local reference table overflow error.

I'm no Android/Java programmer, but I think all of these calls to `CallStringMethod` and `CallObjectMethod` need to have their result deleted via `DeleteLocalRef`.

I think the crash only happens on older/slower Android devices such as the Nexus 5X running Android OS 7.0. I don't think the Android OS matters though, I have seen the crash also on an Xiaomi Mi 8 running Android OS 9.0 device. But haven't seen the crash on any Android OS 8.0 devices.

Here is a subset of the devices that we've seen the crash on:
P9, P9 Lite, Tab A, Intex Aqua Craze, Galaxy Grand 2, S4, Xperia Z2, Le Pro 3, Redmi 4 Pro, Redmi Note 4, Vibe K5.
Almost all of those were running Android OS 7.0.

### Environment

* bugsnag-unity version: 4.2.0
* Unity version: 2017.4.14f1
* Operating system name and version: Windows 10
* Target platform names and versions: Android, on a Nexus 5X running Android OS 7.0
* Initializing bugsnag via the Unity UI or in code? UI

### Example code snippet
To reproduce, you can just open this Unity project, scene "main", then build to your Android device. It will run 20 Bugsnag.Notify() calls which will crash the app. The project is completely empty except for the Bugsnag plugin plus my test code.
https://www.dropbox.com/s/43ssyb4kjrmksb4/TestBugsnag.zip?dl=0

### PR DESCRIPTION
**Pull request by kattrali**
## Goal

Avoid overflowing the reference table on Android when passing objects from the Java to C# layer.

## Changeset

Updated the Android `NativeInterface` function to convert a Java `Map` into a C# `Dictionary` to remove JNI reference once they are done being used.

## Tests

Reproduced the crash reported in #129 by attaching large amounts of metadata on the native side then calling `notify()` using a Nexus 5X running API 23.

## Discussion

Deleting the `valueClass` reference in particular reduces the likelihood of encountering this issue significantly, however, given enough other JNI activity at the same time (hundreds of `notify()` calls at once, other plugins processing large collections of objects) this problem would remain. There doesn't seem to be an API for checking how much of the reference table is still free though.

### Linked issues

Fixes #129

### CODE REVIEW

File: src/BugsnagUnity/Native/Android/NativeInterface.cs [hunk 1]
```diff
@@ -390,9 +390,13 @@ private Breadcrumb ConvertToBreadcrumb(IntPtr javaBreadcrumb)
             dict.AddToPayload(key, AndroidJNI.CallStringMethod(value, ObjectToString, new jvalue[]{}));
           }
           AndroidJNI.DeleteLocalRef(value);
```
Comment (snmaynard) [inline src/BugsnagUnity/Native/Android/NativeInterface.cs]: Out of interest - why is value deleted here rather than outside the if block?

Comment (kattrali) [reply src/BugsnagUnity/Native/Android/NativeInterface.cs]: Calling `DeleteLocalRef` on null causes bad times.

Comment (snmaynard) [reply src/BugsnagUnity/Native/Android/NativeInterface.cs]: and none of the other things can be null?

Comment (kattrali) [reply src/BugsnagUnity/Native/Android/NativeInterface.cs]: Not really no. Given a `Map`, asking for an iterator always returns one. Given an iterator and a `hasNext` check, asking for a `MapEntry` always returns one. Given a `MapEntry`, asking for a `key` always returns one. However, given a `key`, the `value` may be null.

**Comment by miv** [comment]
This is still happening on 4.8.2

```
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115] local reference table dump:
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       511: 0x1384c640 java.lang.String "message"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       510: 0x13861900 java.util.HashMap$HashMapEntry
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       509: 0x1391e4e0 java.util.HashMap$EntryIterator
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       508: 0x1322ef70 java.util.HashMap$EntrySet
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       507: 0x132fa3a0 java.util.HashMap
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       506: 0x1383d440 java.lang.String "Log"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       505: 0x13831e40 java.lang.String "Log"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       504: 0x13813880 java.lang.String "Log"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       503: 0x138032c0 java.lang.String "Log"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       502: 0x137ef240 java.lang.String "Log"
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]   Summary:
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of com.unity3d.player.UnityPlayer$e
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of com.bugsnag.android.Breadcrumb
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       385 of java.lang.Class (4 unique instances)
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]       110 of java.lang.String (50 unique instances)
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of java.util.ArrayList$ArrayListIterator
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of java.util.ArrayList
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of java.util.HashMap$EntryIterator
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of java.util.HashMap$EntrySet
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]         1 of java.util.HashMap$HashMapEntry
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115]        10 of java.util.HashMap (10 unique instances)
04-22 22:57:25.921 13073 13095 F art     : art/runtime/indirect_reference_table.cc:115] 
```
